-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 5.7
-- Sat Feb 17 22:27:02 2018

-- parameterized module component declaration
component DVI_clkgen
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        CLKOS3: out  std_logic);
end component;

-- parameterized module component instance
__ : DVI_clkgen
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, CLKOS3=>__);
