-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 5.7
-- Mon Feb 19 22:37:27 2018

-- parameterized module component declaration
component ADC_PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic);
end component;

-- parameterized module component instance
__ : ADC_PLL
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__);
