-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 5.8
-- Tue Feb 13 18:21:34 2018

-- parameterized module component declaration
component ddr_out
    port (clkop: in  std_logic; clkos: in  std_logic; 
        clkout: out  std_logic; reset: in  std_logic; 
        data: in  std_logic_vector(1 downto 0); 
        dout: out  std_logic_vector(0 downto 0));
end component;

-- parameterized module component instance
__ : ddr_out
    port map (clkop=>__, clkos=>__, clkout=>__, reset=>__, data(1 downto 0)=>__, 
        dout(0 downto 0)=>__);
