-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 5.8
--C:\lscc\diamond\3.9_x64\ispfpga\bin\nt64\scuba.exe -w -n ddr_out -lang vhdl -synth synplify -bus_exp 7 -bb -arch sa5p00 -type iol -mode Transmit -io_type LVCMOS25 -width 1 -freq_in 100 -gear 2 -del -1 -fdc C:/lscc/diamond/3.9_x64/examples/Flea_Ohm_DVI_test/ddr_out/ddr_out.fdc 

-- Tue Feb 13 18:21:34 2018

library IEEE;
use IEEE.std_logic_1164.all;
library ECP5U;
use ECP5U.components.all;

entity ddr_out is
    port (
        clkop: in  std_logic; 
        clkos: in  std_logic; 
        clkout: out  std_logic; 
        reset: in  std_logic; 
        data: in  std_logic_vector(1 downto 0); 
        dout: out  std_logic_vector(0 downto 0));
end ddr_out;

architecture Structure of ddr_out is

    -- internal signal declarations
    signal db0: std_logic;
    signal da0: std_logic;
    signal scuba_vlo: std_logic;
    signal scuba_vhi: std_logic;
    signal sclk_t: std_logic;
    signal buf_clkout: std_logic;
    signal buf_douto0: std_logic;

    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst2_OB : label is "LVCMOS25";
    attribute IO_TYPE of Inst1_OB0 : label is "LVCMOS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst4_ODDRX1F0: ODDRX1F
        port map (SCLK=>sclk_t, RST=>reset, D0=>da0, D1=>db0, 
            Q=>buf_douto0);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    Inst3_ODDRX1F: ODDRX1F
        port map (SCLK=>clkos, RST=>reset, D0=>scuba_vhi, D1=>scuba_vlo, 
            Q=>buf_clkout);

    Inst2_OB: OB
        port map (I=>buf_clkout, O=>clkout);

    Inst1_OB0: OB
        port map (I=>buf_douto0, O=>dout(0));

    db0 <= data(1);
    da0 <= data(0);
    sclk_t <= clkop;
end Structure;
