/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 5.8 */
/* Thu Aug 17 10:09:52 2017 */

/* parameterized module instance */
ddr_out __ (.clkop( ), .clkos( ), .clkout( ), .reset( ), .data( ), 
    .dout( ));
